version: '3'

volumes:
  postgres_data:
      driver: local

networks:
  unleash-network:
    driver: bridge

services:
  
  postgres:
    image: postgres
    container_name: postgres_unleash
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - unleash-network
    environment:
      POSTGRES_DB: unleash
      POSTGRES_USER: unleash_user
      POSTGRES_PASSWORD: unleash_pwd

  unleash:
      image: unleashorg/unleash-server
      container_name: unleash_server
      environment:
        DATABASE_HOST: postgres
        DATABASE_NAME: unleash
        DATABASE_USERNAME: unleash_user
        DATABASE_PASSWORD: unleash_pwd
        DATABASE_SSL: "false"
      ports:
        - "4242:4242"
      networks:
        - unleash-network
      depends_on:
        - "postgres"

